url: https://wo0dyn.me

author:
  fullname:     Nicolas Dubois
  nickname:     wo0dyn
  short-title:  Sr Software Engineer
  title:        Senior Software Engineer (Python/UI)
  company:      Deepki
  location:     Brive-la-Gaillarde area, France
  email:        nicolas.c.dubois@gmail.com
  gravatar:     https://secure.gravatar.com/avatar/51c17cde62e1bb52812ea5352723a5ed
  website:      https://wo0dyn.me

  social:
    bluesky:
      name: Bluesky
      url: https://bsky.app/profile/wo0dyn.bsky.social
      nickname: "@wo0dyn.bsky.social"
    codepen:
      name: CodePen
      url: https://codepen.io/wo0dyn
    facebook:
      name: Facebook
      url: https://facebook.com/wo0dyn
    github:
      name: GitHub
      url: https://github.com/wo0dyn
    google-developers:
      name: Google Developers
      url: https://g.dev/wo0dyn
    instagram:
      name: Instagram
      url: https://instagram.com/wo0dyn
    linkedin:
      name: LinkedIn
      url: https://linkedin.com/in/wo0dyn
    linktree:
      name: Linktree
      url: https://linktr.ee/wo0dyn
    mastodon:
      name: Mastodon
      url: https://mamot.fr/@wo0dyn
      nickname: wo0dyn@mamot.fr
    soundcloud:
      name: SoundCloud
      url: https://soundcloud.com/wo0dyn
    youtube:
      name: YouTube
      url: https://www.youtube.com/@wo0dyn

archives:
  - datetime: 2025-04-23T07:40:13Z
    website: https://wo0dyn.me/
  - datetime: 2018-08-27T15:44:13Z
    website: https://nicolasdubois.com/
  - datetime: 2016-10-21T15:02:07Z
    website: https://nicolasdubois.com/
  - datetime: 2009-11-28T14:52:21Z
    website: http://nico.dubs-family.com:80/home
  - datetime: 2006-11-23T02:25:22Z
    website: http://duboisnicolas.free.fr/cv/personal.php
  - datetime: 2002-02-14T11:54:46Z
    website: http://duboisnicolas.free.fr:80/

safe: true
permalink: /posts/:categories/:year/:title:output_ext
highlighter: rouge

defaults:
  - scope:
      path: ""
    values:
      layout: default
      description: >
        Hi, I'm Nicolas “wo0dyn” Dubois, I'm a Senior Software Engineer (Python/UI),
        guitarist, father of two, and this is my homepage!

plugins:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed

collections:
  talks:
    output: false

exclude:
  - assets/js/LICENSE
  - assets/js/package.json
  - assets/js/README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - homepage.sublime-project
  - README.rst
  - Taskfile.yml
  - vendor/bundle
