url: https://wo0dyn.me

safe: true
permalink: /posts/:categories/:year/:title:output_ext
highlighter: rouge

defaults:
  - scope:
      path: ""
    values:
      layout: default
      description: >
        Hi, I'm Nicolas “wo0dyn” Dubois, I'm a Senior Software Engineer (Python/UI),
        guitarist, father of two, and this is homepage

plugins:
  - jekyll-sitemap

sass:
  style: compressed

collections:
  talks:
    output: false

exclude:
  - assets/js/LICENSE
  - assets/js/package.json
  - assets/js/README.md
  - CNAME
  - homepage.sublime-project
  - README.rst
