safe: true
permalink: /posts/:categories/:year/:title:output_ext
highlighter: rouge

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.rst
  - math.py
  - homepage.sublime-project
  - vendor

sass:
  style: compressed

collections:
  talks:
    output: true

# host: 0.0.0.0
# port: 5000
